Hw solution
MukhailoVorobets/online-bookstore_hw pull request #1
Opened 2024-12-28 19:36 UTC by MukhailoVorobets

2024-12-29 13:10 UTC, okuzan requested changes

2024-12-29 13:10 UTC, okuzan commented on src/main/java/com/example/model/Book.java
> +@Entity
Don't use Lombok's Data on JPA entities, it bundles several annotations, some of which (ToString, EqualsAndHashcode) can be problematic for persisted entities. Use @ Getter Setter for now

2024-12-29 13:10 UTC, okuzan commented on src/main/java/com/example/service/BookServiceImpl.java
> +
either remove empty line after class definition everywhere or keep it everywhere, consistency is key :)

2025-01-04 23:04 UTC, sarakhmen requested changes
let's slightly improve your solution :)

2025-01-04 23:04 UTC, sarakhmen commented on pom.xml
> +			https://raw.githubusercontent.com/mate-academy/style-guides/master/java/checkstyle.xml
I see you have included checkstyle.xml as a file at the root level of your repo, so let's reference this file here instead of web link

2025-01-04 23:04 UTC, sarakhmen commented on src/test/resources/application.properties
> +spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
that's great that you have application.properties for test folder. What about 'main' one?

2025-01-04 23:04 UTC, sarakhmen commented on src/main/java/com/example/repository/BookRepositoryImpl.java
> +            return entityManager.createQuery("SELECT b FROM Book b", Book.class).getResultList();
what about 'catch' section here?

2025-01-04 23:04 UTC, sarakhmen commented on src/main/java/com/example/repository/BookRepositoryImpl.java
> +            throw e;
let's throw an error with clear message here

2025-01-05 14:37 UTC, MukhailoVorobets commented on src/test/resources/application.properties
> +spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
what do you mean?

2025-01-05 19:22 UTC, sarakhmen commented on src/test/resources/application.properties
> +spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
application.properties should be separate for the main ant test folders. Currently you have only one - for test folder

2025-01-05 19:23 UTC, sarakhmen requested changes
add resources folder and application.properties for 'main' folder

2025-01-06 08:46 UTC, liliia-ponomarenko approved these changes
Good job!

2025-01-06 08:46 UTC, liliia-ponomarenko commented on src/main/java/com/example/model/Book.java
> +public class Book {
Let’s  use Lombok annotation

2025-01-13 20:10 UTC, merged